tailwind.config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e4e2dd',
        'surface-container-highest': '#e4e2dd',
        'primary-fixed-dim': '#aec9ed',
        'on-primary': '#ffffff',
        'secondary-container': '#b0d1fd',
        'primary-container': '#0f2d4a',
        secondary: '#3f6086',
        'surface-tint': '#466080',
        'on-secondary-container': '#395a80',
        'outline-variant': '#c3c6ce',
        'on-primary-fixed': '#001d36',
        'surface-container': '#f0eee9',
        surface: '#fbf9f4',
        'primary-fixed': '#d2e4ff',
        'on-secondary': '#ffffff',
        'surface-bright': '#fbf9f4',
        outline: '#73777e',
        'tertiary-container': '#3c2800',
        'secondary-fixed': '#d2e4ff',
        'tertiary-fixed-dim': '#efbf6c',
        error: '#ba1a1a',
        'gold-accent': '#e6af2e',
        'mustard-accent': '#e6af2e',
        primary: '#00182f',
        'on-tertiary-fixed': '#271900',
        'on-background': '#1b1c19',
        'tertiary-fixed': '#ffdeaa',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b68c3f',
        'inverse-primary': '#aec9ed',
        'surface-dim': '#dbdad5',
        'on-secondary-fixed': '#001d36',
        'inverse-on-surface': '#f2f1ec',
        'sand-dark': '#e5dec9',
        'inverse-surface': '#30312e',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-primary-container': '#7a95b7',
        'glass-white': 'rgba(255, 255, 255, 0.95)',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#26496d',
        'on-primary-fixed-variant': '#2e4867',
        'error-container': '#ffdad6',
        tertiary: '#221500',
        'surface-container-high': '#eae8e3',
        background: '#fbf9f4',
        'on-tertiary-fixed-variant': '#5f4100',
        'on-surface-variant': '#43474d',
        'on-surface': '#1b1c19',
        'surface-container-low': '#f5f3ee',
        'status-emerald': '#059669',
        'secondary-fixed-dim': '#a8c9f5',
        'navy-custom': '#0F2942',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-md': '64px',
        'container-max': '1280px',
        'section-lg': '80px',
        gutter: '32px',
        'section-sm': '48px',
        base: '4px',
      },
      fontFamily: {
        'label-meta': ['Assistant', 'sans-serif'],
        'display-hero': ['Assistant', 'sans-serif'],
        'body-main': ['Assistant', 'sans-serif'],
        'accent-serif': ['Playfair Display', 'serif'],
        'display-hero-mobile': ['Assistant', 'sans-serif'],
        'headline-section': ['Assistant', 'sans-serif'],
        'headline-card': ['Assistant', 'sans-serif'],
        'nav-link': ['Assistant', 'sans-serif'],
      },
      fontSize: {
        'label-meta': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'display-hero': ['60px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-main': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'accent-serif': ['18px', { lineHeight: 'normal', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-hero-mobile': ['36px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-section': ['30px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-card': ['20px', { lineHeight: '1.4', fontWeight: '700' }],
        'nav-link': ['15px', { lineHeight: 'normal', fontWeight: '600' }],
      },
    },
  },
};
